version: '3.8'

services:
  mariadb:
    container_name: mariadb
    nertworks:
      inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
      end_file: .env
      args:
        - SQL_DATABASE
        - SQL_ROOT_PW
        - SQL_USER
        - SQL_USER_PW
      volumes:
        mariadb:/var/lib/mysql
      restart: always
      expose:
        3306:3306
