version: '3.8'

services:
  mariadb:
    env_file: .env
    container_name: mariadb
    networks:
      - inception
    volumes:
      - db_volume:/var/lib/mysql
    build:
      context: requirement/mariadb
      dockerfile: Dockerfile
      args:
        - SQL_DATABASE
        - SQL_ROOT_PW
        - SQL_USER
        - SQL_USER_PW
          #    restart: always
    expose:
      - "3306"
  wordpress:
    container_name: wordpress
    env_file: .env
    volumes:
      - wp_volume:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    build:
      context: requirement/wordpress
      args:
        - SQL_DATABASE
        - SQL_ROOT
        - SQL_ROOT_PW
        - SQL_ROOT_MAIL
        - SQL_USER
        - SQL_USER_PW
        - SQL_USER_MAIL
        - DOMAIN_NAME
        - WP_TITLE

      dockerfile: Dockerfile
        #    restart: always
    expose:
      - "9000"
  nginx:
    container_name: nginx
    env_file: .env
    volumes:
      - wp_volume:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    ports:
      - "443:443"
    expose:
      - "443"
    build:
      context: requirement/nginx
      dockerfile: Dockerfile
        #    restart: always
  
volumes:
  db_volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/llevasse/data/mariadb'
  wp_volume:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/llevasse/data/wordpress'

networks:
  inception:
    driver: bridge
