version: "3.8"

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o:  bind
      device: /home/llevasse/data/mariadb
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/llevasse/data/mariadb


services:
  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
    image: nginx
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - inception
    ports:
      - "443:443"
    restart: always

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb/
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_USER_PW: ${DB_USER_PW}
        DB_ROOT_PW: ${DB_ROOT_PW}
    env_file:
      - .env
    image: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
    env_file:
      - .env
    image: wordpress
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - inception
    restart: always
